export let elements = {};

export function initDOMElements() {
    console.debug('Inizializing DOMElements');
    
    elements = {
        timeOutDialog: document.querySelector('#timeout-dialog'),
        yourTurn: document.querySelector('#active-player'),
        counter: document.querySelector('#counter'),
        gameOverDialog: document.querySelector('#game-over-dialog'),
        winnerAnnounce: document.querySelector('#announce-winner'),
        playAgainButton: document.querySelector('#play-again-button'),
        turnBoardTitle: document.querySelector('#turn-board h3'),
        turnBoardActivePlayer: document.querySelector('#turn-board p'),
        boardOne: document.querySelector('.gameboard-1'),
        boardTwo: document.querySelector('.gameboard-2'),
        initialDialog: document.querySelector('#initial-dialog'),
        selectModality: document.querySelector('#modality'),
        choosePlayerOneName: document.querySelector('#player-one'),
        choosePlayerTwoName: document.querySelector('#player-two'),
        startGameButton: document.querySelector('#start-game-btn'),
        backgroundImage: document.querySelector('#background-image'),
        horizontalOne: document.querySelector('#horizontal-1'),
        verticalOne: document.querySelector('#vertical-1'),
        horizontalTwo: document.querySelector('#horizontal-2'),
        verticalTwo: document.querySelector('#vertical-2'),
        shipBoardOne: document.querySelector('#ships-board-1'),
        shipBoardTwo: document.querySelector('#ships-board-2'),
        carrierOne: document.querySelector('#carrier-1'),
        battleshipOne: document.querySelector('#battleship-1'),
        cruiserOne: document.querySelector('#cruiser-1'),
        submarineOne: document.querySelector('#submarine-1'),
        destroyerOne: document.querySelector('#destroyer-1'),
        carrierTwo: document.querySelector('#carrier-2'),
        battleshipTwo: document.querySelector('#battleship-2'),
        cruiserTwo: document.querySelector('#cruiser-2'),
        submarineTwo: document.querySelector('#submarine-2'),
        destroyerTwo: document.querySelector('#destroyer-2'),
        draggableShips: document.querySelectorAll('.ship-container'),
        randomPlaceOne: document.querySelector('#place-randomly-btn-1'),
        randomPlaceTwo: document.querySelector('#place-randomly-btn-2'),
        doneButtonOne: document.querySelector('#done-btn-1'),
        doneButtonTwo: document.querySelector('#done-btn-2'),
        startGameDialog: document.querySelector('#start-game-dialog'),
    };
};
